spring:
  application:
    name:
      AiBook
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false
  config:
    import: classpath:application-secret.yml
server:
  port: 8080

