name: spring ci/cd

on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: set up jdk 21
        uses: actions/setup-java@v4
        with: 
          distribution: 'temurin'
          java-version: '21'

      - name: create application-secret.yml
        run: |
          mkdir -p src/main/resources
          echo ${{ secrets.APPLICATION_SECRET_YML }} | base64 -d > src/main/resources/application-secret.yml

      - name: create application-test.yml
        run: |
          mkdir -p src/test/resources
          echo ${{ secrets.APPLICATION_TEST_YML }} | base64 -d > src/main/resources/application-test.yml

      - name: build with gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean build

      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build and push docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            spring-api-app-image:latest
            # ${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }} # Commit SHA 태그 추가
          file: Dockerfile

      - name: deploy to ec2
        uses: appleboy/ssh-action@v1.0.1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /project

            docker-compose pull

            docker-compose up -d






        
